### ISSUE TITLE
compute_30 architecture is deprecated in new versions of NVCC

### ISSUE THREAD

**Issue by askorikov** [Nebula-simulator/Nebula#2]
At my computer (CUDA Toolkit 11.2) the hard coded `-gencode arch=compute_30,code=compute_30` argument for NVCC makes the build fail due to deprecation. I wonder what you think would be the best way of fixing this? In principle, leaving architecture to NVCC's default value could be a safe choice in this respect, and then interested users can pass the desired architecture explicitly to CMake if needed.

**Comment by lvkessel** [comment]
Thanks for reporting this!

The most straightforward solution is to only compile for compute capability 3.0 when the CUDA toolkit version is less than 11.

As for your suggestion to leave things to default: it seems that `nvcc` defaults to whatever target architecture is the oldest one it supports. It seems there is no easy way to automatically detect the most suitable one for the current hardware.

I looked at a bunch of major software packages, and they all have a big list of `-gencode` flags in their CMake config. As of version 3.18, CMake has a `CUDA_ARCHITECTURES` property which makes it easier to define such a list. But version 3.18 is very recent (July 2020) so I'm not going to use this feature yet. And in any case, we still have to choose our architectures.

I'll figure out which combinations of toolkit/gencode flags we want to support. The current list in `CMakelists.txt` represents whatever hardware we could lay our hands on four years ago. It really needs to be updated.
