### ISSUE TITLE
About Geometry dataset

### ISSUE THREAD

**Issue by ranyang1005** [Nebula-simulator/Nebula#3]
Thanks for your great work of Nebula simulator.
We want to generate a lot of SEM images for further analysis, however, we found it is a huge workload to generate the geometry file.
Is there a ready-to-use geometry dataset available? 
Thanks in advance.
Best regards

**Comment by lvkessel** [comment]
I recognise the fact that generating geometries is not an easy task. Sadly there is no tooling available for that at the moment and it is currently not part of the planning (though that may change in the future). There are several programs out there that can help generating triangle meshes, but we have not looked into converting one of those formats into nebula. Any contributions on that front are of course welcome!

As for a ready-to-use geometry dataset, I can dig up some of my scripts to generate line/space patterns if it helps you.

**Comment by ranyang1005** [comment]
@lvkessel  Thanks a lot for your feedback, I understand current status well.
I will further investigate, and will share to you if I find some useful stuffs.
By now, I am not quite sure whether generating line/space patterns by script is the best ways. If needed, I will contract you.
Thanks again for your kindly response.
