### ISSUE TITLE
nebula_gpu, nebula_cpu_mt and nebula_cpu_edep not found in bin folder

### ISSUE THREAD

**Issue by achmadkhalid** [Nebula-simulator/Nebula#7]
Hi, 

I'm trying to compile nebula and everything seems fine until this line:
`cmake .. -G "MinGW Makefiles" ` (instead of only cmake .. because i have to use an additional generator MinGW) 

The results are shown above:
![image](https://github.com/Nebula-simulator/Nebula/assets/128361402/f4ea20eb-844e-4b1c-95f1-d279ca7388f4)

After that i typed (i use mingw32-make instead of msys-make)
`mingw32-make`
and it results some errors as shown above:
![image](https://github.com/Nebula-simulator/Nebula/assets/128361402/80fb8871-0b6f-4e62-8651-9a672a8a25ae)

I'm curently using Windows 10 as my operating system. I also added MinGW (with ggc 6.3.0), cmake (version 3.27.1) and hdf5 (version 1.14.1) into PATH environment variable. I don't have any GPU available on my PC and using only CPU.

Any suggestions or solutions regarding this particular problem? Do i have to install and use msys-make instead of mingw32 and add it into PATH environment variables? Thanks in advance!

**Comment by lvkessel** [comment]
Looks like your installation of hdf5 is not compatible with your compiler. That would have to be addressed on the hdf5 side, not here. It would appear that the problem you are facing was already around in 2011 (https://forum.hdfgroup.org/t/hdf5-and-mingw/2328). Some googling indicates that people are having to modify hdf5 headers sometimes to make it compatible with mingw, which is not exactly a good sign.

On Windows, I suggest you use visual studio if possible as that is at least officially supported by hdf5.

**Comment by achmadkhalid** [comment]
Hi Ivkessel,

I'll try to take a look at the hdf5/visual studio installation. Thanks for the feedback and anyways thanks for your great work for the Nebula Simulator!
